# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options
#
image: ubuntu:v01

before_script:
    - git checkout -B $CI_COMMIT_REF_NAME

after_script:
    - echo "Done."

variables:
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: recursive

basis_check:
    script:
        - ./build_all.sh
