image: miio/x86-default:latest

before_script:
		- git checkout -B $CI_COMMIT_REF_NAME

after_script:
		- echo "Done."

variables:
		GIT_STRATEGY: fetch
		GIT_SUBMODULE_STRATEGY: recursive

build_all:
		script:
			- ./build_all.sh
